name: poke_dapp
description: A Pokedex Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  domain:
    path: ./domain
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  app_settings: 4.0.3
  cached_network_image: 2.2.0+1
  cupertino_icons: ^0.1.3
  fluro: 1.6.4
  focus_detector: ^1.0.3
  hive: 1.4.4
  intl: 0.17.0
  logger: 0.9.2
  package_info: 0.4.3
  path_provider: 1.6.14
  provider: 4.3.2+1
  timeago: ^2.0.27
  firebase_core: 0.5.2
  firebase_analytics: ^6.0.0
  firebase_crashlytics: 0.2.1+1
  firebase_dynamic_links: ^0.6.2
  dio: ^3.0.9
  rxdart: ^0.24.1

dev_dependencies:
  build_runner: 1.10.3
  hive_generator: 0.8.1
  json_serializable: ^3.4.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: pt_BR